/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/batman.glb -o src/components/models/Batman.jsx 
Author: lmmfs.1998 (https://sketchfab.com/lmmfs.1998)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-batman-40b3ef186877492e80ae5a959613ab71
Title: The Batman
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Batman(props) {
  const { nodes, materials } = useGLTF('/models/batman.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Face_Batman_0.geometry} material={materials.Batman} position={[0, 179.477, 11.246]} scale={3.992} />
      <mesh geometry={nodes.Belt_Batman_0.geometry} material={materials.Batman} position={[0, 176.251, 14.318]} scale={3.992} />
      <mesh geometry={nodes.Armor_Batman_0.geometry} material={materials.Batman} position={[0, 179.477, 11.246]} scale={3.992} />
    </group>
  )
}

useGLTF.preload('/models/batman.glb')
